name: API prod deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
      - .github
      - client/**
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.API_SERVER_HOST }}
        username: ${{ secrets.API_SERVER_USERNAME }}
        password: ${{ secrets.API_SERVER_PASSWORD }}
        script: |
          # Fix NVM appleboy/ssh-action
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh

          cd transport-api-test.na4u.ru/transport
          git checkout main
          git fetch
          git reset --hard origin/main
          git clean -df
          git pull

          export APP_PORT=${{ secrets.API_SERVER_PORT }}
          nvm use
          pnpm -r --filter transport-server --filter transport-common i
          pnpm build:common
          pnpm build:server

          # Start app (BUG: pm2 not working)
          pm2 delete transport-server
          pm2 start node api/build/index.js --name transport-server
