name: API prod deploy
on:
  push:
    branches:
      - test-deploy
    paths-ignore:
      - README.md
      - .gitignore
      - .github
      - client
jobs:
  deploy:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: deploy
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.API_SERVER_HOST }}
        username: ${{ secrets.API_SERVER_USERNAME }}
        password: ${{ secrets.API_SERVER_PASSWORD }}
        script: |
          printenv
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          printenv
          cd transport-api-test.na4u.ru/transport
          printenv
          git reset --hard
          git pull
          nvm use
          pnpm -r --filter transport-server --filter transport-common i
          pnpm build:common
          pnpm build:server
          pm2 delete all
          pm2 start node api/build/index.js --name transport-server
