name: Update public transport transphoto static data
on:
  schedule:
    - cron: "0 22 * * 0"
jobs:
  update-public-transport-transphoto-static-data:
    name: Update
    runs-on: ubuntu-20.04
    steps:
    - name: "run update:transphoto script"
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.API_SERVER_HOST }}
        username: ${{ secrets.API_SERVER_USERNAME }}
        password: ${{ secrets.API_SERVER_PASSWORD }}
        command_timeout: 60m
        script: |
          # Fix NVM appleboy/ssh-action
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh

          cd transport-api-test.na4u.ru/transport
          export STRAPI_EMAIL="${{ secrets.STRAPI_EMAIL }}"
          export STRAPI_PASSWORD="${{ secrets.STRAPI_PASSWORD }}"

          nvm use
          pnpm -r --filter transport-schedulers --filter transport-common i
          pnpm -r --filter transport-schedulers update:transphoto
